version: 2.1

executors:
  default:
    docker:
    - image: cimg/base:2022.02
    environment:
      USER: "circleci"
      TERM: dumb
      PATH: "/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

commands:
jobs:
  build:
    docker:
    - image: cimg/openjdk:11.0.17
    environment:
      PATH: "/home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.daml/bin:/opt/apache-maven/bin"
    steps:
      - checkout
      - run:
          name: install daml
          command: |
            export DAML_VERSION=$(yq eval '.sdk-version' daml.yaml)
            curl -sSL https://get.daml.com/ | sh -s $DAML_VERSION

      - run:
          name: build
          command: |
            daml build
            daml codegen java
            mvn compile

workflows:
  version: 2
  build:
    jobs:
    - build
